# data parameters
expname: map_inpainting
train_data_path: ../dataset/maps_train_inpaint
eval_iter: 2000  # set to 0 to disable
eval_data_path: ../dataset/maps_eval_inpaint
resume:
batch_size: 24
image_shape: [256, 256, 1]  # network input
mask_shape: [256, 256]
spatial_discounting_gamma: 0.95

# training parameters
cuda: True
gpu_ids: [0]
num_workers: 16
warmup_iter: 10000
lr: 0.0001
beta1: 0.5
beta2: 0.9
n_critic: 5
niter: 500000
print_iter: 100
viz_iter: 2000
viz_max_out: 16
snapshot_save_iter: 20000

# loss weight
l1_loss_alpha: 0.5
ae_loss_alpha: 20.0
f1_loss_alpha: 0.2
kl_loss_alpha: 0.5
gan_loss_alpha: 0.0001
wgan_gp_lambda: 20.0

# network parameters
netG:
  input_dim: 1
  ngf: 16

netD:
  input_dim: 1
  ndf: 16
