# data parameters
expname: map_inpainting
train_data_path: ../dataset/maps_train_inpaint
resume:
batch_size: 24
image_shape: [256, 256, 1]
mask_shape: [256, 256]
discounted_mask: True
spatial_discounting_gamma: 0.9

# training parameters
cuda: True
gpu_ids: [0]
num_workers: 16
lr: 0.0001
beta1: 0.5
beta2: 0.9
n_critic: 3
niter: 500000
print_iter: 100
viz_iter: 2000
viz_max_out: 16
snapshot_save_iter: 20000

# loss weight
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.5
ae_loss_alpha: 1.5
global_wgan_loss_alpha: 0.5
gan_loss_alpha: 0.001
wgan_gp_lambda: 10.0

# network parameters
netG:
  input_dim: 1
  ngf: 16

netD:
  input_dim: 1
  ndf: 16
